package com.sunjk.sunjktool.ui.components

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.automirrored.filled.List
import androidx.compose.material.icons.automirrored.filled.TrendingUp
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.automirrored.filled.Send
import androidx.compose.material.icons.automirrored.filled.ExitToApp
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowRight
import androidx.compose.material.icons.automirrored.filled.NoteAdd
import androidx.compose.ui.graphics.vector.ImageVector

/**
 * 笔记本可选图标：图标名 → ImageVector 映射，用于编辑页图标选择器与列表/首页展示。
 * 图标名以字符串存储（便于跨设备同步），解析失败时回退到默认 folder。
 *
 * 本清单为 material-icons-extended 中精选的常用图标（约 200+），涵盖学习、办公、生活、
 * 技术、健康、金融等主题。如需更全可继续扩充。
 */
object NotebookIcons {

    private val ICON_MAP: Map<String, ImageVector> = mapOf(
        // 基础/文件夹
        "folder" to Icons.Filled.Folder,
        "folder_open" to Icons.Filled.FolderOpen,
        "create_new_folder" to Icons.Filled.CreateNewFolder,
        "inbox" to Icons.Filled.Inbox,
        "archive" to Icons.Filled.Archive,
        "bookmarks" to Icons.Filled.Bookmarks,
        "bookmark" to Icons.Filled.Bookmark,
        "bookmark_border" to Icons.Filled.BookmarkBorder,
        "collections_bookmark" to Icons.Filled.CollectionsBookmark,
        "star" to Icons.Filled.Star,
        "star_border" to Icons.Filled.StarBorder,
        "favorite" to Icons.Filled.Favorite,
        "favorite_border" to Icons.Filled.FavoriteBorder,
        "flag" to Icons.Filled.Flag,
        "label" to Icons.Filled.Label,
        "category" to Icons.Filled.Category,
        "grid_view" to Icons.Filled.GridView,
        "dashboard" to Icons.Filled.Dashboard,

        // 学习/阅读
        "school" to Icons.Filled.School,
        "menu_book" to Icons.Filled.MenuBook,
        "book" to Icons.Filled.Book,
        "auto_stories" to Icons.Filled.AutoStories,
        "library_books" to Icons.Filled.LibraryBooks,
        "local_library" to Icons.Filled.LocalLibrary,
        "import_contacts" to Icons.Filled.ImportContacts,
        "history_edu" to Icons.Filled.HistoryEdu,
        "edit" to Icons.Filled.Edit,
        "edit_note" to Icons.Filled.EditNote,
        "note" to Icons.Filled.Note,
        "note_add" to Icons.AutoMirrored.Filled.NoteAdd,
        "description" to Icons.Filled.Description,
        "article" to Icons.Filled.Article,
        "subject" to Icons.Filled.Subject,
        "assignment" to Icons.Filled.Assignment,
        "assignment_turned_in" to Icons.Filled.AssignmentTurnedIn,
        "fact_check" to Icons.Filled.FactCheck,
        "rule" to Icons.Filled.Rule,
        "quiz" to Icons.Filled.Quiz,
        "question_answer" to Icons.Filled.QuestionAnswer,
        "lightbulb" to Icons.Filled.Lightbulb,
        "psychology" to Icons.Filled.Psychology,
        "biotech" to Icons.Filled.Biotech,
        "science" to Icons.Filled.Science,

        // 科学与数学
        "calculate" to Icons.Filled.Calculate,
        "functions" to Icons.Filled.Functions,
        "numbers" to Icons.Filled.Numbers,
        "tag" to Icons.Filled.Tag,
        "percent" to Icons.Filled.Percent,
        "straighten" to Icons.Filled.Straighten,
        "square_foot" to Icons.Filled.SquareFoot,
        "architecture" to Icons.Filled.Architecture,
        "construction" to Icons.Filled.Construction,
        "engineering" to Icons.Filled.Engineering,

        // 技术/编程
        "code" to Icons.Filled.Code,
        "code_off" to Icons.Filled.CodeOff,
        "terminal" to Icons.Filled.Terminal,
        "data_object" to Icons.Filled.DataObject,
        "data_array" to Icons.Filled.DataArray,
        "memory" to Icons.Filled.Memory,
        "developer_mode" to Icons.Filled.DeveloperMode,
        "integration_instructions" to Icons.Filled.IntegrationInstructions,
        "smartphone" to Icons.Filled.Smartphone,
        "computer" to Icons.Filled.Computer,
        "laptop" to Icons.Filled.Laptop,
        "phone_iphone" to Icons.Filled.PhoneIphone,
        "android" to Icons.Filled.Android,
        "rocket" to Icons.Filled.Rocket,
        "rocket_launch" to Icons.Filled.RocketLaunch,
        "bug_report" to Icons.Filled.BugReport,
        "api" to Icons.Filled.Api,
        "cloud" to Icons.Filled.Cloud,
        "cloud_done" to Icons.Filled.CloudDone,
        "storage" to Icons.Filled.Storage,
        "dns" to Icons.Filled.Dns,
        "hub" to Icons.Filled.Hub,
        "share" to Icons.Filled.Share,
        "link" to Icons.Filled.Link,
        "sync" to Icons.Filled.Sync,
        "download" to Icons.Filled.Download,
        "upload" to Icons.Filled.Upload,
        "save" to Icons.Filled.Save,
        "file_download" to Icons.Filled.FileDownload,
        "file_upload" to Icons.Filled.FileUpload,
        "open_in_new" to Icons.Filled.OpenInNew,

        // 艺术/设计
        "palette" to Icons.Filled.Palette,
        "color_lens" to Icons.Filled.ColorLens,
        "brush" to Icons.Filled.Brush,
        "auto_awesome" to Icons.Filled.AutoAwesome,
        "auto_awesome_motion" to Icons.Filled.AutoAwesomeMotion,
        "hexagon" to Icons.Filled.Hexagon,
        "diamond" to Icons.Filled.Diamond,
        "filter_vintage" to Icons.Filled.FilterVintage,
        "spa" to Icons.Filled.Spa,
        "eco" to Icons.Filled.Eco,
        "forest" to Icons.Filled.Forest,
        "park" to Icons.Filled.Park,
        "local_florist" to Icons.Filled.LocalFlorist,
        "emoji_nature" to Icons.Filled.EmojiNature,
        "public" to Icons.Filled.Public,
        "travel_explore" to Icons.Filled.TravelExplore,
        "explore" to Icons.Filled.Explore,
        "map" to Icons.Filled.Map,
        "place" to Icons.Filled.Place,
        "landscape" to Icons.Filled.Landscape,
        "beach_access" to Icons.Filled.BeachAccess,
        "flight" to Icons.Filled.Flight,
        "directions_car" to Icons.Filled.DirectionsCar,
        "train" to Icons.Filled.Train,
        "trending_up" to Icons.AutoMirrored.Filled.TrendingUp,
        "trending_flat" to Icons.Filled.TrendingFlat,
        "trending_down" to Icons.Filled.TrendingDown,
        "waterfall_chart" to Icons.Filled.WaterfallChart,

        // 音乐/娱乐
        "music_note" to Icons.Filled.MusicNote,
        "library_music" to Icons.Filled.LibraryMusic,
        "headphones" to Icons.Filled.Headphones,
        "mic" to Icons.Filled.Mic,
        "movie" to Icons.Filled.Movie,
        "theaters" to Icons.Filled.Theaters,
        "sports_esports" to Icons.Filled.SportsEsports,
        "videogame_asset" to Icons.Filled.VideogameAsset,
        "cake" to Icons.Filled.Cake,
        "celebration" to Icons.Filled.Celebration,
        "emoji_events" to Icons.Filled.EmojiEvents,
        "sports_soccer" to Icons.Filled.SportsSoccer,
        "sports_basketball" to Icons.Filled.SportsBasketball,
        "sports_tennis" to Icons.Filled.SportsTennis,
        "directions_bike" to Icons.Filled.DirectionsBike,
        "pool" to Icons.Filled.Pool,
        "fitness_center" to Icons.Filled.FitnessCenter,
        "self_improvement" to Icons.Filled.SelfImprovement,

        // 健康/医疗
        "health_and_safety" to Icons.Filled.HealthAndSafety,
        "medical_services" to Icons.Filled.MedicalServices,
        "local_hospital" to Icons.Filled.LocalHospital,
        "monitor_heart" to Icons.Filled.MonitorHeart,
        "pregnant_woman" to Icons.Filled.PregnantWoman,

        // 金融/商业
        "account_balance" to Icons.Filled.AccountBalance,
        "account_balance_wallet" to Icons.Filled.AccountBalanceWallet,
        "savings" to Icons.Filled.Savings,
        "payments" to Icons.Filled.Payments,
        "attach_money" to Icons.Filled.AttachMoney,
        "currency_yuan" to Icons.Filled.CurrencyYuan,
        "show_chart" to Icons.Filled.ShowChart,
        "pie_chart" to Icons.Filled.PieChart,
        "bar_chart" to Icons.Filled.BarChart,
        "insights" to Icons.Filled.Insights,
        "leaderboard" to Icons.Filled.Leaderboard,
        "storefront" to Icons.Filled.Storefront,
        "shopping_bag" to Icons.Filled.ShoppingBag,
        "shopping_cart" to Icons.Filled.ShoppingCart,
        "local_mall" to Icons.Filled.LocalMall,
        "work" to Icons.Filled.Work,
        "business_center" to Icons.Filled.BusinessCenter,
        "groups" to Icons.Filled.Groups,
        "group" to Icons.Filled.Group,
        "person" to Icons.Filled.Person,
        "person_outline" to Icons.Filled.PersonOutline,
        "badge" to Icons.Filled.Badge,
        "supervised_user_circle" to Icons.Filled.SupervisedUserCircle,
        "support_agent" to Icons.Filled.SupportAgent,
        "handshake" to Icons.Filled.Handshake,

        // 沟通/消息
        "chat" to Icons.Filled.Chat,
        "chat_bubble" to Icons.Filled.ChatBubble,
        "forum" to Icons.Filled.Forum,
        "mail" to Icons.Filled.Mail,
        "drafts" to Icons.Filled.Drafts,
        "send" to Icons.AutoMirrored.Filled.Send,
        "call" to Icons.Filled.Call,
        "contact_mail" to Icons.Filled.ContactMail,
        "mark_email_read" to Icons.Filled.MarkEmailRead,
        "comment" to Icons.Filled.Comment,

        // 时间/日程
        "schedule" to Icons.Filled.Schedule,
        "event" to Icons.Filled.Event,
        "event_available" to Icons.Filled.EventAvailable,
        "event_busy" to Icons.Filled.EventBusy,
        "event_note" to Icons.Filled.EventNote,
        "calendar_month" to Icons.Filled.CalendarMonth,
        "today" to Icons.Filled.Today,
        "date_range" to Icons.Filled.DateRange,
        "watch_later" to Icons.Filled.WatchLater,
        "access_time" to Icons.Filled.AccessTime,
        "history" to Icons.Filled.History,
        "update" to Icons.Filled.Update,
        "hourglass_empty" to Icons.Filled.HourglassEmpty,
        "hourglass_full" to Icons.Filled.HourglassFull,
        "alarm" to Icons.Filled.Alarm,
        "timer" to Icons.Filled.Timer,
        "pending_actions" to Icons.Filled.PendingActions,
        "task_alt" to Icons.Filled.TaskAlt,
        "checklist" to Icons.Filled.Checklist,
        "check_circle" to Icons.Filled.CheckCircle,
        "check" to Icons.Filled.Check,
        "done_all" to Icons.Filled.DoneAll,
        "verified" to Icons.Filled.Verified,
        "new_releases" to Icons.Filled.NewReleases,
        "warning" to Icons.Filled.Warning,
        "error" to Icons.Filled.Error,
        "info" to Icons.Filled.Info,
        "help" to Icons.Filled.Help,
        "help_outline" to Icons.Filled.HelpOutline,
        "tips_and_updates" to Icons.Filled.TipsAndUpdates,
        "campaign" to Icons.Filled.Campaign,
        "notifications" to Icons.Filled.Notifications,
        "notifications_active" to Icons.Filled.NotificationsActive,
        "pending" to Icons.Filled.Pending,
        "lock" to Icons.Filled.Lock,
        "lock_open" to Icons.Filled.LockOpen,
        "vpn_key" to Icons.Filled.VpnKey,
        "security" to Icons.Filled.Security,
        "verified_user" to Icons.Filled.VerifiedUser,
        "shield" to Icons.Filled.Shield,
        "gpp_good" to Icons.Filled.GppGood,

        // 家居/生活
        "home" to Icons.Filled.Home,
        "cabin" to Icons.Filled.Cabin,
        "cottage" to Icons.Filled.Cottage,
        "house" to Icons.Filled.House,
        "apartment" to Icons.Filled.Apartment,
        "meeting_room" to Icons.Filled.MeetingRoom,
        "restaurant" to Icons.Filled.Restaurant,
        "local_cafe" to Icons.Filled.LocalCafe,
        "fastfood" to Icons.Filled.Fastfood,
        "kitchen" to Icons.Filled.Kitchen,
        "countertops" to Icons.Filled.Countertops,
        "chair" to Icons.Filled.Chair,
        "bed" to Icons.Filled.Bed,
        "weekend" to Icons.Filled.Weekend,
        "pets" to Icons.Filled.Pets,
        "cruelty_free" to Icons.Filled.CrueltyFree,
        "yard" to Icons.Filled.Yard,

        // 购物/服饰
        "checkroom" to Icons.Filled.Checkroom,
        "dry_cleaning" to Icons.Filled.DryCleaning,
        "local_laundry_service" to Icons.Filled.LocalLaundryService,
        "dry" to Icons.Filled.Dry,

        // 交通/物流
        "local_shipping" to Icons.Filled.LocalShipping,
        "inventory_2" to Icons.Filled.Inventory2,
        "receipt_long" to Icons.Filled.ReceiptLong,
        "list" to Icons.AutoMirrored.Filled.List,
        "view_list" to Icons.Filled.ViewList,
        "table_rows" to Icons.Filled.TableRows,
        "list_alt" to Icons.Filled.ListAlt,
        "menu" to Icons.Filled.Menu,
        "more_horiz" to Icons.Filled.MoreHoriz,
        "more_vert" to Icons.Filled.MoreVert,
        "settings" to Icons.Filled.Settings,
        "settings_applications" to Icons.Filled.SettingsApplications,
        "tune" to Icons.Filled.Tune,
        "build" to Icons.Filled.Build,
        "handyman" to Icons.Filled.Handyman,
        "cleaning_services" to Icons.Filled.CleaningServices,
        "delete" to Icons.Filled.Delete,
        "edit_off" to Icons.Filled.EditOff,
        "add" to Icons.Filled.Add,
        "remove" to Icons.Filled.Remove,
        "close" to Icons.Filled.Close,
        "forward" to Icons.Filled.Forward,
        "refresh" to Icons.Filled.Refresh,
        "expand_more" to Icons.Filled.ExpandMore,
        "expand_less" to Icons.Filled.ExpandLess,
        "keyboard_arrow_right" to Icons.AutoMirrored.Filled.KeyboardArrowRight,
        "exit_to_app" to Icons.AutoMirrored.Filled.ExitToApp,
        "arrow_forward" to Icons.AutoMirrored.Filled.ArrowForward
    )

    /** 编辑页可供选择的图标名称（按序展示）。 */
    val selectableNames: List<String> = ICON_MAP.keys.toList()

    /** 根据图标名解析 ImageVector，未知则回退到默认文件夹图标。 */
    fun resolve(name: String): ImageVector = ICON_MAP[name] ?: Icons.Filled.Folder
}
